{
    'name': "AutoFix",
    'author': "Abdo Mohamed",
    'category': "Services",
    'version': '17.0.0.1.0',
    'depends': ['base', 'mail', 'hr', 'account', 'stock', 'purchase'],
    'data': [
        'data/sequence.xml',
        'data/server_actions.xml',
        'data/cron.xml',
        'data/mail_template_data.xml',
        'report/report_actions.xml',
        'report/maintenance_invoice_report.xml',
        'report/inventory_audit_report.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/record_rules.xml',
        'views/car_views.xml',
        'views/service_reception_views.xml',
        'views/work_order_views.xml',
        'views/petty_cash_views.xml',
        'wizard/inventory_audit_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'assets': {
        'web.assets_backend': [
            'autofix/static/src/css/dashboard.css',
            'autofix/static/src/js/dashboard.js',
            'autofix/static/src/xml/dashboard.xml',
        ],
    },
}
