{
    'name': "AutoFix",
    'summary': "Vehicle Service & Repair Workshop Management",
    'author': "Abdo Mohamed",
    'category': "Services",
    'version': '17.0.0.2.0',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'hr', 'account', 'stock', 'purchase'],
    'images': ['static/description/banner.png'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/server_actions.xml',
        'data/cron.xml',
        'data/demo_data.xml',
        'data/mail_template_data.xml',
        'data/record_rules.xml',
        'report/report_actions.xml',
        'report/maintenance_invoice_report.xml',
        'report/inventory_audit_report.xml',
        'report/payroll_report.xml',
        'views/car_views.xml',
        'views/car_brand_views.xml',
        'views/service_type_views.xml',
        'views/service_reception_views.xml',
        'views/work_order_views.xml',
        'views/petty_cash_views.xml',
        'views/vehicle_inspection_views.xml',
        'views/warranty_views.xml',
        'views/appointment_views.xml',
        'views/customer_feedback_views.xml',
        'wizard/inventory_audit_views.xml',
        'wizard/payroll_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'assets': {
        'web.assets_backend': [
            'autofix/static/src/css/dashboard.css',
            'autofix/static/src/js/dashboard.js',
            'autofix/static/src/xml/dashboard.xml',
        ],
    },
}
